### ISSUE TITLE
[database] Identify "Category" data

### ISSUE THREAD

**Issue by shalarewicz** [CGRS-labs/donation-tracker#3]
Decide on information to track for each category

Name, 
id
....

**Comment by shalarewicz** [comment]
On second though may not need to track this in the database but just create a list of constants:

Starter items from Ryan's earlier comments: 
baby formula, diapers, toothbrushes, toothpaste, feminine hygiene products, sleeping bags, and linens. Other items like canned foods, or any ready-to-eat food and energy drinks are also helpful, as well as simple first aid kits.

**Comment by rbhastie** [comment]
Still up for discussion, but currently using this list of categories in the select menu of the AddItem form: 

const categories = ['Childcare', 'Clothing', 'Education', 'Food', 'Healthcare', 'Homegoods', 'Personal hygiene', 'Other']

**Comment by shalarewicz** [comment]
Categories now live in categories.js
